ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
    CREATE USER CAMPUSADMIN IDENTIFIED BY 1; 
    GRANT DBA TO CAMPUSADMIN;
    GRANT EXECUTE ANY PROCEDURE TO CAMPUSADMIN; 
    GRANT CREATE SESSION TO CAMPUSADMIN; 
    GRANT CREATE USER TO CAMPUSADMIN;
    GRANT CREATE ROLE TO CAMPUSADMIN;
    GRANT CONNECT TO CAMPUSADMIN WITH ADMIN OPTION;