-- GIANGVIEN VIEW PRIVILEGE
GRANT SELECT ON CAMPUSADMIN.UV_INFOR TO GIANGVIEN;
GRANT SELECT ON CAMPUSADMIN.sinhvien TO GIANGVIEN;
GRANT SELECT ON CAMPUSADMIN.DONVI TO GIANGVIEN;
GRANT SELECT ON CAMPUSADMIN.HOCPHAN TO GIANGVIEN;
GRANT SELECT ON CAMPUSADMIN.KHMO TO GIANGVIEN;


GRANT UPDATE ON CAMPUSADMIN.NHANSU TO GIANGVIEN;


--SELECT * FROM USER_TAB_PRIVS WHERE TABLE_NAME = 'NHANSU';

GRANT UPDATE ON CAMPUSADMIN.NHANSU TO GIANGVIEN;

-- tao viet xem dang ki co ma gv cua minh
CREATE OR REPLACE VIEW CAMPUSADMIN.uv_DANGKYBANTHAN AS
SELECT * FROM CAMPUSADMIN.DANGKY WHERE MAGV = sys_context('USERENV', 'SESSION_USER');



