-- NHANVIENCOBAN VIEW PRIVILEGE
GRANT SELECT ON CAMPUSADMIN.UV_INFOR TO NHANVIENCOBAN;
GRANT SELECT ON CAMPUSADMIN.sinhvien TO NHANVIENCOBAN;
GRANT SELECT ON CAMPUSADMIN.DONVI TO NHANVIENCOBAN;
GRANT SELECT ON CAMPUSADMIN.HOCPHAN TO NHANVIENCOBAN;
GRANT SELECT ON CAMPUSADMIN.KHMO TO NHANVIENCOBAN;


GRANT UPDATE ON CAMPUSADMIN.NHANSU TO NHANVIENCOBAN;


SELECT * FROM USER_TAB_PRIVS WHERE TABLE_NAME = 'NHANSU';

GRANT UPDATE ON CAMPUSADMIN.NHANSU TO NHANVIENCOBAN;
GRANT NHANVIENCOBAN TO NV08;

GRANT UPDATE(DT) ON CAMPUSADMIN.NHANSU TO NV08;
REVOKE UPDATE ON CAMPUSADMIN.NHANSU FROM NV08;


