
CREATE OR REPLACE VIEW UV_INFOR
AS SELECT* FROM CAMPUSADMIN.NHANSU WHERE MANV = USER;
/


CREATE OR REPLACE VIEW UV_SELPHANCONG
AS SELECT* FROM CAMPUSADMIN.PHANCONG WHERE MAHP IN (SELECT MAHP FROM CAMPUSADMIN.HOCPHAN WHERE MADV = (SELECT MADV FROM CAMPUSADMIN.DONVI WHERE TENDV = N'V?N PH�NG KHOA'));
/

CREATE OR REPLACE VIEW UV_SELDANGKY
AS SELECT* 
   FROM CAMPUSADMIN.DANGKY 
   WHERE NAM = TO_CHAR(SYSDATE, 'YYYY') AND 
        (TO_CHAR(CURRENT_DATE, 'DD') BETWEEN '01' AND '14' AND TO_CHAR(CURRENT_DATE, 'MM') IN ('01', '03', '09')); -- First 14 days of January, March, and September)
/
GRANT SELECT ON CAMPUSADMIN.UV_SELDANGKY TO GIAOVU
/ 

CREATE OR REPLACE VIEW UV_SELPHANCONG_TRUONGDONVI
AS  SELECT* 
    FROM CAMPUSADMIN.PHANCONG 
    WHERE MAHP IN ( SELECT MAHP 
                    FROM CAMPUSADMIN.HOCPHAN 
                    WHERE MADV IN   (SELECT MADV 
                                    FROM CAMPUSADMIN.DONVI 
                                    WHERE TRGDV = USER));
/

GRANT SELECT ON UV_SELPHANCONG_TRUONGDONVI TO TRUONGDONVI;
/

CREATE OR REPLACE VIEW UV_SELDANGKY_4TEST
AS SELECT* 
   FROM CAMPUSADMIN.DANGKY 
   WHERE NAM = TO_CHAR(SYSDATE, 'YYYY');
/

CREATE OR REPLACE VIEW UV_PHANCONG_GV
AS SELECT* FROM CAMPUSADMIN.PHANCONG WHERE MAGV = USER;

GRANT SELECT ON CAMPUSADMIN.UV_PHANCONG_GV TO TRUONGDONVI;
/
CREATE OR REPLACE TRIGGER UTR_DELPHANCONG
BEFORE DELETE
ON CAMPUSADMIN.PHANCONG
FOR EACH ROW
BEGIN
 DELETE FROM CAMPUSADMIN.DANGKY
 WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/
CREATE OR REPLACE VIEW UV_PHANCONG_OF_DONVI
AS SELECT* FROM CAMPUSADMIN.PHANCONG WHERE MAGV IN (SELECT MANV FROM CAMPUSADMIN.NHANSU WHERE MADV IN (SELECT MADV FROM CAMPUSADMIN.DONVI WHERE TRGDV = USER))
/
GRANT SELECT ON UV_PHANCONG_OF_DONVI TO TRUONGDONVI;
/

-- GIAO VU
GRANT SELECT ON CAMPUSADMIN.KHMO TO GIAOVU;
GRANT SELECT ON CAMPUSADMIN.HOCPHAN TO GIAOVU;
GRANT SELECT ON CAMPUSADMIN.DONVI TO GIAOVU;
GRANT SELECT ON SINHVIEN TO GIAOVU;
GRANT SELECT, INSERT ON DANGKY TO GIAOVU;
GRANT SELECT ON CAMPUSADMIN.UV_SELDANGKY TO GIAOVU;    
GRANT SELECT ON CAMPUSADMIN.UV_SELDANGKY_4TEST TO GIAOVU;
GRANT DELETE ON CAMPUSADMIN.DANGKY TO GIAOVU;
GRANT INSERT ON SINHVIEN TO GIAOVU;

GRANT DELETE ON SINHVIEN TO GIAOVU;
GRANT UPDATE ON SINHVIEN TO GIAOVU;
GRANT SELECT ON PHANCONG TO GIAOVU;
GRANT SELECT ON UV_INFOR TO GIAOVU;

GRANT UPDATE ON CAMPUSADMIN.PHANCONG TO GIAOVU;
GRANT SELECT ON CAMPUSADMIN.UV_SELPHANCONG TO GIAOVU;

-- TRUONG DV
GRANT SELECT ON CAMPUSADMIN.UV_INFOR TO TRUONGDONVI;
GRANT SELECT ON CAMPUSADMIN.SINHVIEN TO TRUONGDONVI;
GRANT SELECT ON CAMPUSADMIN.DONVI TO TRUONGDONVI;
GRANT SELECT ON CAMPUSADMIN.HOCPHAN TO TRUONGDONVI;
GRANT SELECT ON CAMPUSADMIN.KHMO TO TRUONGDONVI;
GRANT SELECT ON CAMPUSADMIN.PHANCONG TO TRUONGDONVI;
GRANT INSERT ON CAMPUSADMIN.PHANCONG TO TRUONGDONVI;
GRANT DELETE ON CAMPUSADMIN.PHANCONG TO TRUONGDONVI;
GRANT UPDATE ON CAMPUSADMIN.PHANCONG TO TRUONGDONVI;

