-- X�a b?ng DANGKY
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DANGKY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng PHANCONG
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PHANCONG CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng KHMO
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE KHMO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng HOCPHAN
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOCPHAN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng SINHVIEN
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SINHVIEN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng NHANSU
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NHANSU CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- X�a b?ng DONVI
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DONVI CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/